[build]
  command = "npm run build:client && npm run build:backend"
  functions = "netlify/functions"
  publish = "backend/dist/spa"


[functions]
  external_node_modules = ["express", "multer", "firebase-admin", "@google/generative-ai", "openai", "uuid", "cors", "dotenv", "zod"]
  node_bundler = "esbuild"
  included_files = ["backend/dist/**"]
  
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
